# Generated by Django 4.1.3 on 2025-10-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='idAlumno',
            new_name='id',
        ),
    ]
